### PR TITLE
allow sha like branch names

### PR DESCRIPTION
**Pull request by mambocab**
This adds some Python 3 compatability stuff on top of #389. It also addresses @ptnapoleon's comments on that PR.

@ptnapoleon can you review? and @mikefero I'd welcome your feedback if you want to have a look.

I tested this code on Python 2 and 3 using this script:

https://gist.github.com/mambocab/445012d260e71cfcbca6

### CODE REVIEW

**Comment by mikefero** [comment]
:+1: Thanks for taking on the review requests; much cleaner

**Comment by ptnapoleon** [comment]
+1 on the code. Have you checked to make sure this works, even after the changes? I'm worried about substring matching with the `git_branch in branches` logic. Also, this helped with review, but Jim can you squash all your changes into one commit, so there are only 2 here?

**Comment by mambocab** [comment]
> Have you checked to make sure this works, even after the changes?

Yep. Running the linked test script results in the output here (which I've cleaned up for readability; the full output is at the same gist):

https://gist.github.com/mambocab/99d9db4107ba3a0499d5#file-fero-out-shorter

`branches` is a list of strings, so `if branch in branches` checks membership, not substring matching.

**Comment by mambocab** [comment]
And yes, happy to squash.

**Comment by mambocab** [comment]
Squashed.

**Comment by ptnapoleon** [comment]
Yes, I know it only checks membership, that was my fear. But if it works, then I'm merging.

**Pull request merged**
