### PR TITLE
Subprocess failure fix

### PR DESCRIPTION
**Pull request by smccarthy788**
@mambocab, please review. I multiplexed one of the test failures you pointed out here: https://cassci.datastax.com/view/Parameterized/job/parameterized_dtest_multiplexer/233/

### CODE REVIEW

**Comment by smccarthy788** [comment]
@mambocab, @ptnapoleon: bump.

**Comment by ptnapoleon** [comment]
I'm +1

**Comment by ptnapoleon** [comment]
What c* ticket is this for?

**Comment by smccarthy788** [comment]
Not sure if there is a ticket. It came up in a dev build: http://cassci.datastax.com/job/tjake-11752-2.2-dtest/1/testReport/junit/sstable_generation_loading_test/TestSSTableGenerationAndLoading/sstableloader_compression_none_to_deflate_test/

**Comment by ptnapoleon** [comment]
I'm going to go ahead and merge then?

**Pull request merged**
