### PR TITLE
Windows fix

### PR DESCRIPTION
**Pull request by ptnapoleon**
@jorgebay and @josh-mckenzie to review

### CODE REVIEW

**Comment by ptnapoleon** [comment]
Only review the relevant commit. I accidentally included both. @mambocab, can you review the `wait=True` change?

**Comment by josh-mckenzie** [comment]
+1 on VerifyPorts check

**Comment by mambocab** [comment]
Before the `if wait:` block in this method, there's a

```python
        if capture_output:
            p = subprocess.Popen(args, env=env, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
            stdout, stderr = p.communicate()
```

I believe that `.communicate` blocks, so passing `capture_output=True` and `wait=False` would lead to unexpected behavior, where it waits on `communicate` even though `wait` was false. Maybe add an assertion that arguments don't contradict each other.

Other than that, +1.

**Comment by jorgebay** [comment]
Tested on Windows for C* 1.2, 2.0, 3.0.0-rc1. ps1 / bat windows fix looks good!

Thanks @ptnapoleon

**Comment by ptnapoleon** [comment]
@mambocab Is the new commit what youre looking for?

**Comment by mambocab** [comment]
Yup, it is.

**Pull request merged**
