### PR TITLE
Allow passing in literal yaml to updateconf

### PR DESCRIPTION
**Pull request by ptnapoleon**
@tolbertam to review

### CODE REVIEW

**Comment by ptnapoleon** [comment]
```
a:
- b:
  - c
  - d
```

achieved by
`ccm updateconf -y 'a: [b: [c,d]]'`

**Comment by tolbertam** [comment]
Sorry I haven't had a chance to look at this recently, will take a look soon.

**Comment by thibaultCha** [comment]
This would be a very handy feature :+1:

**Comment by ptnapoleon** [comment]
@mambocab Can you review when you get a chance?

**Comment by mambocab** [comment]
I've confirmed that you get the expected behavior with `ccm updateconf -y 'a: [b: [c,d]]'` and `ccm updateconf -y 'auto_bootstrap: true'`. Code looks good too. You might reword the documentation a bit -- something like "If enabled, treat argument as literal yaml, not key-value pairs". It's not obvious that `-y` is a flag that flips a bit, rather than an option that itself takes an argument.

**Pull request merged**
