### PR TITLE
handle failure in dse shell-out methods

### PR DESCRIPTION
**Pull request by mambocab**
This adds the handling added in #510 to DSE methods.

It's not clear to me how the C\* counterparts in `node.py` are tested. What should I do to test these changes? They work locally for me.

This is a breaking API change.

### CODE REVIEW

**Comment by mambocab** [comment]
Oh, side note: the `handle_external_tool_process` requires an argument list in addition to the process being handled, because `Popen` objects don't persist this data [until the addition of `Popen.args` in Python 3.3](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.args). 

One way to slightly improve this function would be to use a custom `Popen` subclass as suggested in [this StackOverflow answer](https://stackoverflow.com/questions/33258684/python-how-to-get-command-run-with-subprocess-popen). I'd be happy to throw this together for this PR.

**Comment by mambocab** [comment]
Just fixed this -- `Popen` objects weren't redirecting output; this fixes that.

**Comment by ptnapoleon** [comment]
> One way to slightly improve this function would be to use a custom Popen subclass as suggested in this StackOverflow answer. I'd be happy to throw this together for this PR.

This seems unnecessary? Unless it's more than just ugly that we're passing in the list of args as well

**Comment by mambocab** [comment]
> This seems unnecessary? Unless it's more than just ugly that we're passing in the list of args as well

Nope, just an unnecessarily ugly API. For now, there's nothing it prevents us from doing.

**Pull request merged**
