### PR TITLE
Timeout param node start

### PR DESCRIPTION
**Pull request by mambocab**
This makes the `wait_other_notice` and `wait_for_binary_proto` params able to specify timeouts if they are integers.

### CODE REVIEW

**Comment by knifewine** [comment]
looks sensible to me. maybe we run a big dtest job on this branch just to make sure there's no surprises?

**Comment by knifewine** [comment]
that aside, +1

**Comment by ptnapoleon** [comment]
+1. Will run on dtest first, out of respect for process

**Comment by mambocab** [comment]
I have fixed the many, many mistakes I made and I think this is ready for re-review. I'll start a fresh CI run.

**Comment by ptnapoleon** [comment]
Already started a fresh CI run.

**Comment by ptnapoleon** [comment]
CI went great, will merge after rebase/squash

**Pull request merged**
