### PR TITLE
Support byteman startup scripts when calling start()

### PR DESCRIPTION
**Pull request by ostefano**
I am working on a new test in cassandra-dtest where I need to submit a byteman rule to a single node,  after restarting it. Might not be the best way, so I am open to suggestions.

### CODE REVIEW

**Comment by ptnapoleon** [comment]
Hi @ostefano. Forgive me, but I don't really know how the byteman integration in C* works. Why can't you simply set `node.byteman_startup_script` before calling `start()`?

**Comment by ostefano** [comment]
Hi @ptnapoleon , that would not work because `byteman_startup_script` needs to be part of the configuration file, and setting the class member does not update it (it is only updated when `__update_envfile` is called by the node constructor).

**Comment by ptnapoleon** [comment]
Okay. Then, for code re-uses sake, maybe let's just add a method `node.update_startup_byteman_script` that changes the class member and runs __update_envfile (or import_config_files)?

**Comment by ostefano** [comment]
Sure, sounds good to me. Pushed commit e70cd78

**Pull request merged**
