### PR TITLE
uses `nodetool info` to get node's data size

### PR DESCRIPTION
**Pull request by mambocab**
I've deferred the calculation itself to a "private" function for testability.

### CODE REVIEW

**Comment by mambocab** [comment]
If merged, will fix #244.

**Comment by ptnapoleon** [comment]
Seeing as how we are changing API here, because `data_size()` no longer accepts live_data as an argument, please point this at develop and not master.

Thank you for the test.

**Comment by mambocab** [comment]
I could add a dummy `live_data` parameter.

Also, that `info=None` parameter shouldn't be there, I'll remove that before merge.

**Comment by ptnapoleon** [comment]
It would be more pythonic to add `args` and `kwargs` to filter out old parameters.

**Comment by mambocab** [comment]
Then we'd have to hand-roll error-checking for spurious arguments. I was thinking something like

```
def data_size(live_data=None):
     if live_data is not None:
         warnings.warn("The 'live_data' keyword argument is deprecated.", DeprecationWarning)
    ...
```

Which wouldn't affect the behavior of arbitrary arguments.

But! sending a PR to `develop` is fine too. Whichever is best for ccm.

**Comment by ptnapoleon** [comment]
I would say I at least want this retargeted to `develop`, then I'll roll it up with some other issues into a minor release. I also like your deprecation solution, that is better than `**kwargs`

**Comment by mambocab** [comment]
Closing; #247 is the real deal.

**Pull request closed without merging**
