### PR TITLE
Overwrite in.sh on upgrade. Closes #463

### LINKED ISSUE #463: Upgrade / Downgrade of node leaves previous jamm jar version in configs
While adding sstableupgrade_test in dtest, I found that when the jamm jar version changes between 2.0 and 2.1 Cassandra branches, CCM does not handle the configuration updates fully during upgrade/downgrade of a node, leaving the old jamm jar version in the configs. I'll work on repro steps and add them here, but I believe that this comes from the env setup in ccmlib/common.py.

### PR DESCRIPTION
**Pull request by ptnapoleon**
Testing locally before merging. @iamaleksey to review, please

### CODE REVIEW

**Comment by ptnapoleon** [comment]
I've run CI on this, and nothing fails that wasn't failing already. Going to go ahead and merge this w/o waiting for US reviewers to wake up.

**Comment by bjmb** [comment]
Looks like this commit is making our tests in appveyor fail: https://ci.appveyor.com/project/DataStax/python-driver/build/1528/job/j82bjrm0cwvq4a8o#L1479 . 
We can start a cluster and remove it but when we try to start it again there's an error starting the nodes.
Seems fine in linux.

**Comment by ptnapoleon** [comment]
Damn. :(. We can.... gate the if check on OS? That will leave in the upgrade bug on windows, but fix the issue you're seeing?

**Comment by bjmb** [comment]
Yeah I think that would be a solution for us, also allowing this might be OK since probably not that many people would run into the bug on Windows.

**Comment by bjmb** [comment]
Thanks, they are back to normal.

**Pull request merged**
